# Generated by Django 4.0 on 2021-12-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOnWork', models.BooleanField(default=False)),
                ('isOffWork', models.BooleanField(default=False)),
                ('isHome', models.BooleanField(default=False)),
            ],
        ),
    ]
