# Generated by Django 4.0 on 2021-12-12 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chulgun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schmst',
            name='isOffWork',
        ),
        migrations.AddField(
            model_name='schmst',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 6, 21, 12, 769553)),
        ),
    ]
